GambitRefreshList/Pages/AssignedAsset.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using GambitRefreshList.Models;

namespace GambitRefreshList.Pages
{
    public class AssignedReplacement : PageModel
    {
        private readonly GambitRefreshList.Models.GambitContext _context;

        public AssignedReplacement(GambitRefreshList.Models.GambitContext context)
        {
            _context = context;
        }

        public IList<Itasset> Itasset { get; set; }
        public IList<AssetReplacementLookup> assets { get; set; }
        public IList<RefreshedComputer> RefreshedComputer { get; set; }

        public string SearchTerm { get; set; }
        [BindProperty]
        public int NewAssetId { get; set; }

        public int OldAssetId { get; set; }

        
        public async Task<IActionResult> OnPostSubmit()
        {
            var assetassignment = new AssetReplacementLookup();
            //add asset
            var assetid = Request.Form["item.Id"];
            var formid = Request.Form["id"];
            NewAssetId = Int32.Parse(assetid[0]);
            OldAssetId = Int32.Parse(formid[0]);
            
            //delete old associates
            var all = _context.AssetReplacementLookups.Where(d => d.OldAsset == OldAssetId);
            _context.AssetReplacementLookups.RemoveRange(all);
            if(all == null)
            {

                return RedirectToPage("./NotFound");

            }

            await _context.SaveChangesAsync();

            assetassignment.NewAsset = NewAssetId;
            assetassignment.OldAsset = OldAssetId;

            _context.AssetReplacementLookups.Add(assetassignment);
            _context.Entry(assetassignment).State = Microsoft.EntityFrameworkCore.EntityState.Added;
            await _context.SaveChangesAsync();
            return RedirectToPage("./Index");
          
        }
        [BindProperty(SupportsGet = true)] public string OldID { get; set; }
        public async Task<IActionResult> OnGetAsync(string OldID)
        {

            Itasset = await _context.Itassets.Where(b => b.Replacement == 1).ToListAsync();
            
            OldAssetId = Int32.Parse(OldID);
            var OldName = await _context.Itassets.FirstAsync(b => b.Id == OldAssetId);
            ViewData["OldAssetId"] = OldAssetId;
            ViewData["Name"] = OldName.Name;
            if (OldID == null)
            {
                return RedirectToPage("./NotFound");
            }
            if (Itasset == null)
            {
                return RedirectToPage("./NotFound");
            }
    
            return Page();
        }
    }
}

GambitRefreshList/Pages/AssignedAssetInfo.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using GambitRefreshList.Models;

namespace GambitRefreshList.Pages
{
    public class AssignedAssetInfoModel : PageModel
    {
        private readonly GambitRefreshList.Models.GambitContext _context;

        public AssignedAssetInfoModel(GambitRefreshList.Models.GambitContext context)
        {
            _context = context;
        }

        public AssetReplacementLookup AssetReplacementLookup { get; set; }
        [BindProperty(SupportsGet = true)] public string OldID { get; set; }
        public async Task<IActionResult> OnGetAsync(int? OldID)
        {

        

            if (OldID == null)
            {
                return RedirectToPage("./NotFound");
            }
            var OldName = await _context.Itassets.FirstAsync(b => b.Id == OldID);
            ViewData["Name"] = OldName.Name;

            AssetReplacementLookup = await _context.AssetReplacementLookups
                .Include(a => a.NewAssetNavigation)
                .Include(a => a.OldAssetNavigation).FirstOrDefaultAsync(m => m.OldAsset == OldID);

            if (AssetReplacementLookup == null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }
    }
}

GambitRefreshList/Pages/AssignedReplacement.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GambitRefreshList.Models;

namespace GambitRefreshList.Pages
{
    public class AssignedReplacementModel : PageModel
    {
        private readonly GambitRefreshList.Models.GambitContext _context;
        public IList<Itasset> Itasset { get; set; }
        public IList<AssetReplacementLookup> assets { get; set; }

        public AssignedReplacementModel(GambitRefreshList.Models.GambitContext context)
        {
            _context = context;
        }

        [BindProperty]
        public AssetReplacementLookup AssetReplacementLookup { get; set; }
        public int NewAssetId { get; set; }

        public int OldAssetId { get; set; }
        public async Task<IActionResult> OnGetAsync(int? id)
        {

            assets = await _context.AssetReplacementLookups
                .Include(a => a.NewAssetNavigation)
                .Include(a => a.OldAssetNavigation).ToListAsync();
            if (assets == null)
            {
                return RedirectToPage("./NotFound");
            }


            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            //_context.Attach(AssetReplacementLookup).State = EntityState.Modified;

            try
            {
                var assetid = Request.Form["item.NewAssetNavigation.Id"];
                var oldformid = Request.Form["item.OldAssetNavigation.Id"];
                NewAssetId = Int32.Parse(assetid[0]);
                OldAssetId = Int32.Parse(oldformid[0]);

                //delete old associates
                var all = _context.AssetReplacementLookups.Where(d => d.OldAsset == OldAssetId);

                //set replacement flag bit inactive
                var replacement = _context.Itassets.FirstOrDefault(b => b.Id == NewAssetId);
                if (replacement != null)
                {
                    replacement.Replacement = 1;
                }

                _context.AssetReplacementLookups.RemoveRange(all);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!AssetReplacementLookupExists(AssetReplacementLookup.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./AssignedReplacement");
        }

        private bool AssetReplacementLookupExists(int id)
        {
            return _context.AssetReplacementLookups.Any(e => e.Id == id);
        }
    }
}

GambitRefreshList/Pages/CompletedComputer.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using GambitRefreshList.Models;

namespace GambitRefreshList.Pages
{
    public class CompletedComputerModel : PageModel
    {

        [BindProperty]
        public int NewAssetId { get; set; }
        public int OldAssetId { get; set; }



        private readonly GambitRefreshList.Models.GambitContext _context;

        public CompletedComputerModel(GambitRefreshList.Models.GambitContext context)
        {
            _context = context;
        }

        public IList<AssetReplacementLookup> AssetReplacementLookup { get;set; }

        public async Task OnGetAsync()
        {
            AssetReplacementLookup = await _context.AssetReplacementLookups
                .Include(a => a.NewAssetNavigation)
                .Include(a => a.OldAssetNavigation).ToListAsync();
        }
        public async Task<IActionResult> OnPostAsync()
        {
            try
            {
                //add asset
                var assetid = Request.Form["item.NewAssetNavigation.Id"];
                var oldformid = Request.Form["item.OldAssetNavigation.Id"];
                NewAssetId = Int32.Parse(assetid[0]);
                OldAssetId = Int32.Parse(oldformid[0]);

                //find associate record owner
                //insert new owner association
                var replacement = _context.AssignedAssets.FirstOrDefault(b => b.AssetId == OldAssetId);
                var previousperson = replacement.EmployeeId;
               // var previousid = replacement.AssetId;
                if (replacement != null)
                {
                    replacement.EmployeeId = 322;
                    await _context.SaveChangesAsync();

                }

                //set current employee in it asset
                /*
                var newasset = _context.Itassets.FirstOrDefault(b => b.Id == NewAssetId);
               
                // var previousid = replacement.AssetId;
                if (replacement != null)
                {
                    newasset.EmployeeId = previousperson;
                    await _context.SaveChangesAsync();

                }
                */

                AssignedAsset assignedowner = new AssignedAsset();
                assignedowner.EmployeeId = previousperson;
                assignedowner.AssetId = NewAssetId;
                await _context.SaveChangesAsync();

                _context.AssignedAssets.Add(assignedowner);
                _context.Entry(assignedowner).State = Microsoft.EntityFrameworkCore.EntityState.Added;
                
                
             

                var deploy = _context.AssetReplacementLookups.FirstOrDefault(b => b.OldAssetNavigation.Id == OldAssetId);
                if (deploy != null)
                {
                    _context.AssetReplacementLookups.RemoveRange(deploy);
                }
                await _context.SaveChangesAsync();

                //return Page();
                return RedirectToPage("./CompletedComputer");
            }
            catch (Exception e)
            {
                return RedirectToPage("./NotFound");
            }

        }
    }
}

GambitRefreshList/Pages/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using GambitRefreshList.Models;

namespace GambitRefreshList.Pages
{
    public class CreateModel : PageModel
    {
        private readonly GambitRefreshList.Models.GambitContext _context;

        public CreateModel(GambitRefreshList.Models.GambitContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            ViewData["Branch"] = new SelectList(_context.BranchLks, "Id", "Branch"); 
            ViewData["Location"] = new SelectList(_context.LocationLks, "Id", "Description");
            ViewData["BranchId"] = new SelectList(_context.BranchLks, "Id", "Id");
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "Id", "DisplayName");
            ViewData["LocationId"] = new SelectList(_context.LocationLks, "Id", "Id");
            ViewData["VendorId"] = new SelectList(_context.VendorLks, "Id", "VendorName");
            ViewData["DeviceTypeDrop"] = new SelectList(_context.DeviceTypeLks, "Id", "Desciption");
            return Page();
        }

        [BindProperty]
        public Itasset Itasset { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            //insert qty from model
            try
            {
                int qty = Int32.Parse(Request.Form["Qty"]);
                var laptopflag = "";
                if (Itasset.DeviceTypeId == 2)
                {
                    laptopflag = "L";
                }
               
                if (qty <= 10)
                {
                    for (int i = 0; i <  qty; i++)
                    {
                        //figure out naming convention and apply it
                        using (var context = new GambitContext())
                        {
                            var itasset = new Itasset();
                            var name = _context.PreferenceLks.SingleOrDefault(b => b.Preference == "ComputerNameSchema").PreferenceValue +
                            laptopflag +
                            "-" +
                            context.PreferenceLks.SingleOrDefault(b => b.Preference == "ComputerName").PreferenceValue;
          
                            itasset.Manufacturer = Itasset.Manufacturer;
                            itasset.LocationId = Itasset.LocationId;
                            itasset.Model = Itasset.Model;
                            itasset.BranchId = Itasset.BranchId;
                            itasset.DeviceTypeId = Itasset.DeviceTypeId;
                            itasset.Name = name;
                            itasset.Replacement = 1;
                            itasset.OperatingSystem = Itasset.OperatingSystem;
                            itasset.PurchasedOn = Itasset.PurchasedOn;
                            itasset.Bskponumber = Itasset.Bskponumber;
                            itasset.VendorId = Itasset.VendorId;

                            //add asset
                            context.Itassets.Add(itasset);
                            context.Entry(itasset).State = Microsoft.EntityFrameworkCore.EntityState.Added;
                            //update the end counters  
                            var result = context.PreferenceLks.SingleOrDefault(b => b.Preference == "ComputerName");
                            if (result != null)
                            {
                                int incrementedcomputer = Int32.Parse(result.PreferenceValue) + 1;
                                result.PreferenceValue = $"{incrementedcomputer:0000}";
                                context.Entry(result).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                            }
                            context.SaveChanges();
                        }                      
                    }
                }
            }

            catch
            {
                throw;
               //return RedirectToPage("./NotFound");
            }
            return RedirectToPage("./Index");
        }
    }
}

GambitRefreshList/Pages/DoNotRefreshList.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using GambitRefreshList.Models;

namespace GambitRefreshList.Pages
{
    public class DoNotRefreshListModel : PageModel
    {
        private readonly GambitRefreshList.Models.GambitContext _context;

        public DoNotRefreshListModel(GambitRefreshList.Models.GambitContext context)
        {
            _context = context;
        }

        public IList<Itasset> Itasset { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
          
            Itasset = await _context.Itassets
                .Include(i => i.Branch)
                .Include(i => i.DeviceType)
                .Include(i => i.Location)
                .Include(i => i.Vendor).Where(a => a.DoNotRefresh == 1).ToListAsync();
                 
            if (Itasset == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            //_context.Attach(AssetReplacementLookup).State = EntityState.Modified;

            try
            {
                var assetid = Request.Form["item.Id"];
            
                //set donotshow flag bit inactive
                var donotshow = _context.Itassets.FirstOrDefault(b => b.Id == Int32.Parse(assetid[0]));
                if (donotshow != null)
                {
                    donotshow.DoNotRefresh = null;
                }

              
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
            }

            return RedirectToPage("./DoNotRefreshList");
        }

    }
}

GambitRefreshList/Pages/NotFound.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GambitRefreshList.Pages
{
    public class NotFoundModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

GambitRefreshList/Pages/AssignedAsset.cshtml
@page "{OldID:int}"
@model GambitRefreshList.Pages.SearchITAsset

@{
    Layout = "Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Search IT Assets</title>
</head>
<body>
    Assigning Replacement Asset For: @ViewData["Name"]
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.RefreshedComputer[0].Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RefreshedComputer[0].Manufacturer)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RefreshedComputer[0].Size)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RefreshedComputer[0].Model)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RefreshedComputer[0].OperatingSystem)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.RefreshedComputer[0].PurchasedOn)
                </th>

                <th> Assign Asset </th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model.Itasset)
            {
                <form method="post">
                    <tr>
                        <td>
                            @Html.HiddenFor(modelItem => item.Id)
                            @Html.Hidden("id", (int)ViewData["OldAssetId"])

                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Manufacturer)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Size)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Model)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.OperatingSystem)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PurchasedOn)
                        </td>
                        <td>
                            <input type="submit" value="Assign Asset" asp-page-handler="Submit" />
                        </td>
                    </tr>
                </form>
            }
        </tbody>
    </table>

    <div>
        <a asp-page="./Index" class="btn btn-primary">Go Home</a>
    </div>
</body>
</html>

GambitRefreshList/Pages/AssignedAssetInfo.cshtml
@page "{OldID:int}"
@model GambitRefreshList.Pages.AssignedAssetInfoModel

@{
    Layout = "Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AssignedAssetInfo</title>
</head>
<body>

    <div>
        <h4>Asset for: @ViewData["Name"]</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.AssetReplacementLookup.NewAssetNavigation)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.AssetReplacementLookup.NewAssetNavigation.Id)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.AssetReplacementLookup.OldAssetNavigation)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.AssetReplacementLookup.OldAssetNavigation.Id)
            </dd>
        </dl>
    </div>
    <div>
        <a asp-page="./Index">Home</a>
    </div>
</body>
</html>

GambitRefreshList/Pages/AssignedReplacement.cshtml
@page
@model GambitRefreshList.Pages.AssignedReplacementModel


@{
    Layout = "Shared/_Layout.cshtml";
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Assigned Replacements</title>
</head>
<body>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Old Asset
                </th>
                <th>
                    New Asset   
                </th>
                <th>
                    Remove Assignment
                </th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model.assets)
            {
                <form method="post">
                    <tr>
                        <td>
                            @Html.HiddenFor(modelItem => item.NewAssetNavigation.Id)
                            @Html.HiddenFor(modelItem => item.OldAssetNavigation.Id)

                            @Html.DisplayFor(modelItem => item.OldAssetNavigation.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NewAssetNavigation.Name)
                        </td>

                        <td>
                            <input type="submit" value="Remove Asset" asp-page-handler="Submit" />
                        </td>
                    </tr>
                </form>
            }
        </tbody>
    </table>

    <div>
        <a asp-page="./Index" class="btn btn-primary">Go Home</a>
    </div>
</body>
</html>

GambitRefreshList/Pages/CompletedComputer.cshtml
@page
@model GambitRefreshList.Pages.CompletedComputerModel

@{
    ViewData["Title"] = "Deploy Computers";
}

<h1>Deploy Computers</h1>


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Assigned Replacements</title>
</head>
<body>
    <table class="table">
        <thead>
            <tr>
                <th>
                Old Asset
                </th>
                <th>
                New Asset
                </th>
                <th>
                    Deploy Assignment
                </th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model.AssetReplacementLookup)
            {
                <form method="post">
                    <tr>
                        <td>
                            @Html.HiddenFor(modelItem => item.NewAssetNavigation.Id)
                            @Html.HiddenFor(modelItem => item.OldAssetNavigation.Id)

                            @Html.DisplayFor(modelItem => item.OldAssetNavigation.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NewAssetNavigation.Name)
                        </td>

                        <td>
                            <input type="submit" value="Deploy Asset" asp-page-handler="Submit" />
                        </td>
                    </tr>
                </form>
            }
        </tbody>
    </table>

    <div>
        <a asp-page="./Index" class="btn btn-primary">Go Home</a>
    </div>
</body>
</html>

GambitRefreshList/Pages/DoNotRefreshList.cshtml
@page
@model GambitRefreshList.Pages.DoNotRefreshListModel

@{
    ViewData["Title"] = "DoNotRefreshList";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Do Not Refresh List</title>
</head>
<body>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Asset
                </th>
                <th>
                    Remove Assignment
                </th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model.Itasset)
            {
                <form method="post">
                    <tr>
                        <td>
                            @Html.HiddenFor(modelItem => item.Id)
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                  

                        <td>
                            <input type="submit" value="Allow Refresh" asp-page-handler="Submit" />
                        </td>
                    </tr>
                </form>
            }
        </tbody>
    </table>

    <div>
        <a asp-page="./Index" class="btn btn-primary">Go Home</a>
    </div>
</body>
</html>

GambitRefreshList/Pages/NotFound.cshtml
@page
@model GambitRefreshList.Pages.NotFoundModel
@{
    <h2> The item you were looking for was not found</h2>

    <br/>
    <br/>
    <a asp-page="./Index" class="btn btn-primary">Go Home</a>
}

GambitRefreshList/Pages/SearchITAsset.cshtml
@page "{OldID:int}"
@model GambitRefreshList.Pages.SearchITAsset

@{
    Layout = "Shared/_Layout.cshtml";
 
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Search IT Assets</title>
</head>
<body>
    Assigning Replacement Asset For: @ViewData["Name"]
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.RefreshedComputer[0].Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RefreshedComputer[0].Manufacturer)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RefreshedComputer[0].Size)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RefreshedComputer[0].Model)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RefreshedComputer[0].OperatingSystem)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.RefreshedComputer[0].PurchasedOn)
                </th>

                <th> Assign Asset </th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model.Itasset)
            {
                <form method="post">
                    <tr>
                        <td>
                            @Html.HiddenFor(modelItem => item.Id)
                            @Html.Hidden("id", (int)ViewData["OldAssetId"])

                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Manufacturer)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Size)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Model)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.OperatingSystem)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PurchasedOn)
                        </td>
                        <td>
                            <input type="submit" value="Assign Asset" asp-page-handler="Submit" />
                        </td>
                    </tr>
                </form>
            }
        </tbody>
    </table>

    <div>
        <a asp-page="./Index" class="btn btn-primary">Go Home</a>
    </div>
</body>
</html>